#!/usr/bin/env bash
# Configure Nginx to include the X-Served-By custom header in the response
sudo apt-get -y update
sudo apt-get -y install nginx
# Inject the header directive after the 'listen 80 default_server;' line
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
