#!/usr/bin/env bash
# Install and configure HAproxy to load balance between two web servers
sudo apt-get -y update
sudo apt-get -y install haproxy

# Append the configuration to the haproxy.cfg file
# This defines the frontend (listener) and backend (servers) with roundrobin
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend www-http
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 6885-web-01 18.206.255.103:80 check
    server 6885-web-02 18.233.156.110:80 check
EOF

# Restart HAproxy to load the new config
sudo service haproxy restart
