#!/usr/bin/env bash
# Transfers a file to a server using scp

# Check if 4 arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE=$1
IP=$2
USER=$3
SSH_KEY=$4

# Execute the scp command
# -o StrictHostKeyChecking=no: Disables SSH host key prompt
# -i: Specifies the identity file (private key)
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USER@$IP:~/"
