#!/usr/bin/env bash
# Transfers a file to a server using scp

# Check if 4 arguments are provided
if [ "$#" -ne 4 ]; then
    # The error message MUST be exactly this string
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    # You MUST exit with a non-zero status
    exit 1
fi

# Assign arguments to variables
FILE=$1
IP=$2
USER=$3
SSH_KEY=$4

# Execute the scp command
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USER@$IP:~/"
