#!/usr/bin/env bash
# Transfers a file to a server using scp

# Check if the number of arguments is correct
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables for clarity
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfer the file using scp
# -o StrictHostKeyChecking=no disables the prompt for host key verification
# -i specifies the identity file (private key)
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
